### ISSUE TITLE
Packages updated with errors

### ISSUE THREAD

**Issue by mirashif** [buresdv/Cork#114]
This is the first time I tried updating packages. 

<img width="1012" alt="image" src="https://github.com/buresdv/Cork/assets/34467318/37350cb7-4443-4c1a-b8d7-e20d7a12b40d">

**Comment by buresdv** [comment]
Hey, thanks for reporting. This is not a Cork problem, these are messages that come from Homebrew itself and would happen even if you updated the packages using the command line.

Rather than hiding them, I wanted to show them to the users in case something goes _really_ wrong. This sheet comes up if packages were updated, but some of them complained for whatever reason. Most of the time, you can just ignore these errors.

Did some of your packages not get updated at all?

**Comment by mirashif** [comment]
I think it might be related to password requirement. 
<img width="1012" alt="image" src="https://github.com/buresdv/Cork/assets/34467318/3d79f4e3-a3d4-43ae-a187-e48f84a09ee2">

**Comment by buresdv** [comment]
This specific problem has been fixed in version 1.4.1
