### ISSUE TITLE
Add extra instruction step for Sonoma/Xcode 15

### ISSUE THREAD

**Issue by RWCoding58** [buresdv/Cork#158]
In Xcode 15 (which is required if using the Sonoma Beta), there is an additional step between "Distribute App" and "Copy App" (seen below). You must select the "Custom" option before it takes you to the "Copy App" option.
![Screenshot 2023-09-05 at 13 26 43@2x](https://github.com/buresdv/Cork/assets/87898490/4ce4a717-bdc4-4edb-aee2-ab583af7daff)
Just thought you might want to add this to the README in case people using the beta get confused.

**Comment by zenminimalist** [comment]
Just wanted to leave a comment of appreciation here for @buresdv to say thanks for the compiling instructions. 

I've never seen so easy to follow instruction to compile your own app. I'm not a dev, nor can I program, but it feels badass to be able to compile your "own" app ☺️

**Comment by buresdv** [comment]
@RWCoding58 thanks for the report, I have a README with updated instructions ready to be pushed a couple days after Sonoma comes out. I don't want to push it yet since not many people are using the beta :)

@zenminimalist thanks! Contrary to what everyone assumes, I'm not actully a programmer, I only code in my spare time. My actual job is technical writing for software (basically writing manuals for business software), so making hard things easy to understand is what I do all day 😁

**Comment by zenminimalist** [comment]
> My actual job is technical writing for software (basically writing manuals for business software), so making hard things easy to understand is what I do all day 😁

Well, you're in the job for sure 😎
