### ISSUE TITLE
Export settings to 

### ISSUE THREAD

**Issue by networkshokunin** [buresdv/Cork#240]
# Feature Suggestion

## Mandatory Information
**Description**
What would you like to see added?
1. Scheduled Maintenance
2. iCloud Settings sync
3. Able to backup settings (and packages installed) in a rc file.

**Type**
Are you suggesting a UI or non-UI improvement?
UI

**Mockups**
If you are suggesting a UI feature, do you have any mockups of how you want you feature to look?

## Optional Information
**Additional Information**
Anything you'd like to add?

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
Hey, thanks for the ideas.

The backing up fo installed pakages and added taps is implemented by #227. The rest will take time, especially exporting of settings and iCloud sync, since I'll have to rewrite the way they are saved.


Nevertheless, this is something that's planned for sure. I will keep updating this issue

**Comment by buresdv** [comment]
iCloud syncing was rejected by the community (#242), scheduled maintenance is tracked by #241, and backups have been implemented
