### ISSUE TITLE
Support "untar anywhere" Homebrew installations

### ISSUE THREAD

**Issue by sourcedelica** [buresdv/Cork#259]
# Feature Suggestion

## Mandatory Information
Support "untar anywhere" Homebrew installations.  

I have a locked-down corporate Mac and they don't provide Homebrew in the catalog of apps that we can install.  Neither do I have sudo.  

I installed Homebrew using the [Untar Anywhere](https://docs.brew.sh/Installation#untar-anywhere-unsupported) method.  When I start Cork it just hangs with the spinners on the UI spinning.  I'm guessing it expects Homebrew to be installed in the standard location.

**Type**
Are you suggesting a UI or non-UI improvement?  
Mostly non-UI but there will need to be a setting for the installation directory.

## Checklist
- [X] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
Thanks for the idea. This is, in essence a problem of there not being a way to pick any arbitrary location for Homebrew. This way of installing Homebrew is unsupported (as the docs themselves say), so this is, unfortunately, not a high priority issue at the moment, since there are a few other problems with letting users choose arbitrary locations for Homebrew (mostly security concerns).

Still, the option to choose arbitrary folders for Homebrew installations in in the roadmap; just not with a high priority

**Comment by sourcedelica** [comment]
Thank you for your consideration!

**Comment by buresdv** [comment]
Implemented in 032b26e2f1e4019283cc6271361bb0a89d51de17

**Comment by sourcedelica** [comment]
That's great!  Thanks!  Can't wait to try it out!
