### ISSUE TITLE
Allow updating individual outdated formulae

### ISSUE THREAD

**Issue by benadamstyles** [buresdv/Cork#29]
Maybe this is already possible and I missed it in the UI?

**Comment by buresdv** [comment]
This is not planned for the time being, but I'll keep it written down and come back to it later

**Comment by buresdv** [comment]
@benadamstyles I've decided to reopen this issue and will work on implementing this now :)

**Comment by buresdv** [comment]
Could be accomplished with the `brew reinstall [formula]` and `brew reinstall --cask [cask]` command.

Things to consider
- [ ] Implementing a new sheet for this, **OR** adapting the installation sheet. Former would be difficult because it would need its own boilerplate, the latter because it would require making the install process even more bloated. **Its own sheet would probably be better.**
- [ ] Does this pull the dependencies again? Test on `fontforge`

**Comment by buresdv** [comment]
@benadamstyles This feature is now implemented on the branch `updating-individual-packages` 😊
