### ISSUE TITLE
UI Issue: Text should wrap

### ISSUE THREAD

**Issue by palaniraja** [buresdv/Cork#53]
if you are not aware, i ran into this "Brew Maintenance"

<img width="2092" alt="Screenshot 2023-03-14 at 5 11 02 PM" src="https://user-images.githubusercontent.com/124864/225373521-a5d07831-1d6a-4207-9881-53027d5b7bab.png">

**Comment by buresdv** [comment]
Thank you, I will look into it. The sizing of these sheets has been a pain in the ass, so I'll see what I can do.

**Comment by buresdv** [comment]
Can you try this build? It's not the fix I originally had in mind, but it should work. Please send me a screenshot of how it looks.
[Cork.zip](https://github.com/buresdv/Cork/files/10982999/Cork.zip)

**Comment by buresdv** [comment]
Can you try this build? It's not the fix I originally had in mind, but it should work. Please send me a screenshot of how it looks.
(Had to post this again because I noticed I got the phrasing for the message wrong, this build fixes it)
[Cork.zip](https://github.com/buresdv/Cork/files/10983304/Cork.zip)

**Comment by palaniraja** [comment]
Looks like a reasonable workaround 👍🏽 


<img width="900" alt="Screenshot 2023-03-15 at 1 18 29 PM" src="https://user-images.githubusercontent.com/124864/225432469-bef3adff-3249-4f34-99e3-ddb237165189.png">

**Comment by buresdv** [comment]
Thank you, it looks exactly like it should :)
