### ISSUE TITLE
Enhancement: Keyboard Shortcuts

### ISSUE THREAD

**Issue by Jerry23011** [buresdv/Cork#94]
Just an idea, I noticed that `Start Maintenance` has the shortcut ⌘M, and macOS's default shortcut for ⌘M is minimize window. Also, Cork uses ⌘W & ⌘Q to quit the app. I'm thinking that maybe ⌘W could be used to close the window only.

**Comment by buresdv** [comment]
I didn't know about the ⌘M, because I have not heard anyone ever use it 😅 What other hotkey would you suggest for the maintenance feature?

Speaking of the ⌘W and ⌘Q, they both do the same thing because Cork closes itself completely after the window is closed. I'm following Apple's recommendations on this one, because Cork can only ever have one window open (it's not possible to open more than one window), so you're supposed to quit the app when the window closes. One solution I can think of would be to disable the ⌘W shortcut, what do you think about that?

**Comment by Jerry23011** [comment]
> One solution I can think of would be to disable the ⌘W shortcut

In that case, I think sticking with the current one is better.

> What other hotkey would you suggest for the maintenance feature?

Could be ⌥⌘M? Just like the one for adding a tap.

**Comment by buresdv** [comment]
> Could be ⌥⌘M? Just like the one for adding a tap.

That hotkey is already used for `Delete Cached Downloads` though 🤔

**Comment by Jerry23011** [comment]
How about ⇧⌘M?

**Comment by buresdv** [comment]
I think that could work, I'll implement it
