### ISSUE TITLE
Integrate with Brewlet (menu bar app)

### ISSUE THREAD

**Issue by sh95014** [buresdv/Cork#96]
Have you considered integrating with the [Brewlet](https://github.com/zkokaja/Brewlet) project? Seems like Cork can be a “full UI” that Brewlet can launch for more complex tasks, and there may be code-reuse/sharing opportunities as well.

And if that’s not feasible, consider this a feature request to add a menu bar presence to Cork.

**Comment by buresdv** [comment]
That's an interesting proposition. I had no idea this project existed.

I've had suggestions to implement menu bar items before, but nobody could ever come up with any ideas about what to put in there. I'm not such a big fan of menu bar apps, so I didn't think about it myself.

I will not have the time to write to the project maintainers myself due to a lot of stuff happening at my job lately, so if you'd be up to writing them a message in my place, it would help me a lot. I think the "full UI" idea you proposed would a great approach.

**Comment by sh95014** [comment]
Sure. I’ll try to find some time to learn more about both Cork and Brewlet and propose something. But as Brewlet is presumably talking to brew.sh in its own way, maybe adding a menu bar item to Cork is the sensible thing.

UI-wise, I think Brewlet might be trying to do too much in the menu bar. I do like the idea of an icon in the menu bar that indicates updates are available, though…
